### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by kuzmichevdima** [nurmhit/Text_Generator#16]
python3 train.py --input-dir ../gen_tests --model model

Traceback (most recent call last):
  File "train.py", line 47, in <module>
    input = sys.stdin if args.i is None else open(args.i, "r")
IsADirectoryError: [Errno 21] Is a directory: '../gen_tests'

**Comment by nurmhit** [comment]
Странно, сейчас разберусь, остальное вроде пофиксил!

**Comment by nurmhit** [comment]
Вроде пофиксил с помощью другого решения!
